name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install (skip if no package.json)
        if: hashFiles('package.json') != ''
        run: npm ci

      - name: Test (skip if no package.json)
        if: hashFiles('package.json') != ''
        run: npm test --if-present
